id = "toolang"
name = "Toolang"
version = "0.0.5"
schema_version = 1
authors = ["Brice Yan"]
description = "Toolang syntax highlighting for Zed"
repository = "https://github.com/openhat-ai/zed-toolang"

[grammars.toolang]
repository = "https://github.com/openhat-ai/tree-sitter-toolang"
# tree-sitter-toolang tag: v0.0.5
commit = "3890af3917ecc133a78b77bb5ff26b57029767d9"
