id = "toolang"
name = "Toolang"
version = "0.3.4"
schema_version = 1
authors = ["Brice Yan"]
description = "Toolang syntax highlighting for Zed"
repository = "https://github.com/openhat-ai/zed-toolang"

[grammars.toolang]
repository = "https://github.com/openhat-ai/tree-sitter-toolang"
# tree-sitter-toolang tag: v0.3.3
commit = "053c7ca4b50d060bb2f3ec91b438073f27cea696"
